import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { useEffect, useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	const [title, setTitle] = useState('loading...');
	const [list, setList] = useState([]);

	useEffect(() => {
		// Fetch data from Flask API, runs console.log(data) twice
		// because the call is being made for SSR (server side rendering)
		// and CSR (client side rendering) by default in NextJS

		fetch('http://127.0.0.1:8080/api/home')
			.then((response) => response.json())
			.then((data) => {
				setTitle(data.title);
				setList(data.list);
			});
	}, []);

	return (
		<>
			<Head>
				<title>Hello Next Flask</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='https://fav.farm/⚛' />
			</Head>
			<main className={`${styles.main} ${inter.className}`}>
				<div className={styles.center}>
					<h1>{title}</h1>
					<p>
						{list.map((phrase, index) => {
							let style = {};
							// Conditionally style every other phrase
							if (index % 2 !== 0) {
								style = {
									fontWeight: 'bold',
									fontSize: '22px'
								};
							}

							return (
								// return the phrase within the p tag
								<span key={index} style={style}>
									{phrase}
								</span>
							);
						})}
					</p>
				</div>
			</main>
		</>
	);
}
